---
title: "NB"
author: "Yifei Tang"
date: "2017Äê4ÔÂ9ÈÕ"
output: html_document
---

```{r}
setwd("C:/Users/yftang/Documents/GitHub/Spr2017-proj4-team-5/lib/")
library(stringr)
```


```{r}
data.lib="../data/nameset"
data.files=list.files(path=data.lib, "*.txt")

data.files

## remove "*.txt"
query.list=substring(data.files, 
                     1, nchar(data.files)-4)

query.list

## add a space
query.list=paste(substring(query.list, 1, 1), 
                 " ", 
                 substring(query.list, 
                           2, nchar(query.list)),
                 sep=""
                 )

query.list

```

```{r}
f.line.proc=function(lin, nam.query="."){

  # remove unwanted characters
  char_notallowed <- "\\@#$%^&?" # characters to be removed
  lin.str=str_replace(lin, char_notallowed, "")

  # get author id
  lin.str=strsplit(lin.str, "_")[[1]]
  author_id=as.numeric(lin.str[1])
  
  # get paper id
  lin.str=lin.str[2]
  paper_id=strsplit(lin.str, " ")[[1]][1]
  lin.str=substring(lin.str, nchar(paper_id)+1, nchar(lin.str))
  paper_id=as.numeric(paper_id)
  
  # get coauthor list
  lin.str=strsplit(lin.str, "<>")[[1]]
  coauthor_list=strsplit(lin.str[1], ";")[[1]]

  #print(lin.str)
  for(j in 1:length(coauthor_list)){
      if(nchar(coauthor_list[j])>0){
        nam = strsplit(coauthor_list[j], " ")[[1]]
        if(nchar(nam[1])>0){
          first.ini=substring(nam[1], 1, 1)
        }else{
          first.ini=substring(nam[2], 1, 1)
        }
      }
      last.name=nam[length(nam)]
      nam.str = paste(first.ini, last.name)
      coauthor_list[j]=nam.str
  }
  
  match_ind = charmatch(nam.query, coauthor_list, nomatch=-1)
  
  # print(nam.query)
  # print(coauthor_list)
  # print(match_ind)
  
  if(match_ind>0){
    
    coauthor_list=coauthor_list[-match_ind]
  }
  
  paper_title=lin.str[2]
  journal_name=lin.str[3]
  
  list(author_id, 
       paper_id, 
       coauthor_list, 
       paper_title, 
       journal_name)
}
```

```{r}
data_list=list(1:length(data.files))

for(i in 1:length(data.files)){
  
  ## Step 0 scan in one line at a time.
  
  dat=as.list(readLines(paste(data.lib, data.files[i], sep="/")))
  data_list[[i]]=lapply(dat, f.line.proc, nam.query=query.list[i])
  
}



```

```{r,warning=FALSE}
# Nameset AKumar
num.paper<-length(lengths(data_list[[2]]))

# data_list[[2]][[214]][[3]]

auther.id<-c()
coauther<-list()
auther.info<-NULL


for(i in 1:num.paper){
   auther.id[i]<-data_list[[2]][[i]][[1]]
   coauther[i]<-list(data_list[[2]][[i]][[3]])
}

auther.info<-list(auther.id = auther.id, coauther = coauther)
auther.paper.number<-table(factor(auther.info$auther.id))

 coauther_for_id<-NULL
 paper_num_for_id<-NULL
 id.info<-NULL
 
 
for(j in levels(factor(auther.info$auther.id))){
  coauther_for_id[j]<-list(auther.info$coauther[auther.info$auther.id==j])
  paper_num_for_id[j]<-length(coauther_for_id[[j]])
}
id.info<-list(id = levels(factor(auther.info$auther.id)),coauther =coauther_for_id)
# id.info$coauther[id.info$id==11]
```

```{r,warning=FALSE}
##### id = 11####
prob<-NULL
for(i in 1:paper_num_for_id[11]){
  
        index<-NULL
        
  for(m in 1:length(unique(id.info$coauther[id.info$id==11][[1]])) ){
        index[m] <- sum(id.info$coauther[id.info$id==11][[1]][[i]]==
                      unique(id.info$coauther[id.info$id==11])[[1]][[m]])==
                      length(id.info$coauther[id.info$id==11][[1]][[i]])
  }
  prob[i]<-sum(index)/paper_num_for_id[11]
}
prob



##### id = 6####
prob<-NULL
for(i in 1:paper_num_for_id[6]){
  
        index<-NULL
        
  for(m in 1:length(unique(id.info$coauther[id.info$id==6][[1]])) ){
        index[m] <- sum(id.info$coauther[id.info$id==6][[1]][[i]]==
                      unique(id.info$coauther[id.info$id==6])[[1]][[m]])==
                      length(id.info$coauther[id.info$id==6][[1]][[i]])
        prob[m]<-sum(index)/paper_num_for_id[6]
  }
 # prob[m]<-sum(index)/paper_num_for_id[6]
}
prob



#  for(m in 1:length(unique(id.info$coauther[id.info$id==6][[1]])) ){
#         index[m] <- sum(id.info$coauther[id.info$id==6][[1]][[8]]==
#                       unique(id.info$coauther[id.info$id==6])[[1]][[m]])==
#                       length(id.info$coauther[id.info$id==6][[1]][[8]])
#   }
# index

```

```{r}
# Nameset AGupta
num.paper<-length(data_list[[1]])

auther.id<-NULL
coauther<-NULL
for(i in 1:num.paper){
   auther.id[i]<-data_list[[1]][[i]][[1]]
   coauther<-unique(c(coauther,data_list[[1]][[i]][[3]]))
}

df<-data.frame(auther.id)

num.coauther<-length(coauther)

get.coauther<-function(i){
     coauthers<-rep(0,num.coauther)
     for(j in 1:length(data_list[[1]][[i]][[3]])){
     coauthers[which(data_list[[1]][[i]][[3]][j]==coauther)]<- 1
}
return(coauthers) 
}
##########################################################
#### build dataframe for auther coauther information######
##########################################################
id_co<-NULL
for(i in 1:num.paper){
  id_co<-rbind(id_co,get.coauther(i))
}
colnames(id_co)<-coauther
df<-cbind(auther.id,id_co) 
#df contains the auther coauther information in nameset 1: AGupta


##################################
#### probability calculation######
##################################
id.num.co<-apply(df[,-1],1,sum)
df<-as.data.frame(cbind(id.num.co,df))
freq.id<-as.data.frame(table(df$auther.id)/length(df$auther.id)) 
# numbers of paper for each id
colnames(freq.id)<-c("auther.id","Freq")
num.id<-dim(freq.id)[1]

###################################
#########get.prob function#########
###################################
get.prob<-function(j){
  # Input: auther.id: j
  # Output: P(A|X)
  data <- df[df$auther.id==j,]
  paper.num<-dim(data)[1]
  p_0<-sum(data$id.num.co==0)/paper.num  
  # p_0:  P(N|X)
  p_1<-1-p_0  
  # p_1:  P(Co|X)
  data.with.co<-data[(data$id.num.co==0)==0,] # keep the data for auther that has coauther
  num.with.co<-dim(data.with.co)[1]
  
################################
######find identical function###
################################
  find.identical<-function(i){
   # Input: i-th entry of one auther j
    index<-NULL
    for(m in 1:dim(data.with.co)[1]){
     index[m]<-sum(data.with.co[i,-c(1,2)] != data.with.co[m,-c(1,2)])==0
    }
    label<-ifelse((sum(index) == 1),FALSE,TRUE)
    return(label)
  }
  
seen<-NULL
for(l in 1:num.with.co){
 seen[l]<- find.identical(l)
}
data.seen<-data.with.co[seen==TRUE,]
data.unseen<-data.with.co[seen==FALSE,]

p_s_cx<-dim(data.seen)[1]/num.with.co
p_u_cx<-1-p_s_cx

colsum<-as.matrix(apply(data.with.co,2,sum))
total.num.co<-dim(data)[1]
p_a_scx<-colsum/total.num.co    #### P(A|Seen,Co,X)
p_a_scx<-p_a_scx[-c(1,2),]
p_a_ucx<-1/(num.coauther -total.num.co)  #### P(A|Unseen,Co,X)

outcome<-list(P.N.X = p_0,
              P.Co.X = p_1,
              P.S.Co.X = p_s_cx,
              P.U.Co.X = p_u_cx,
              P.Ak.S.Co.X = p_a_scx,
              P.Ak.U.Co.X = p_a_ucx
              )

return(outcome)
}
# get.prob function end


# para<-list(P.N.X = NULL,
#               P.Co.X = NULL,
#               P.S.Co.X = NULL,
#               P.U.Co.X = NULL,
#               P.Ak.S.Co.X = NULL,
#               P.Ak.U.Co.X = NULL)
para<-NULL
for(i in seq(num.id)){
  para[i]<-list(get.prob(i))
}
para

```







```{r}


###########test sum of prob##################
p_Ak_X<-NULL
for(k in 1:paper.num){
p_Ak_X[k]<-p_1*(p_a_scx[k] * prob.seen[[k]]$p_s_1 + p_a_ucx * prob.seen[[k]]$p_s_0)
}
prod(p_Ak_X)


target<-function(i){
    ln.p.cx<-log(get.prob(i))+log(freq.id[i,2])
    return(ln.p.cx)
}

```

